-- PostgreSQL. Rewritten in place from the original MySQL version when the
-- project moved databases: no PostgreSQL database had applied it yet, so the
-- never-edit rule did not apply. From here on it is applied, and the rule holds.
CREATE TABLE users (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username)
);

-- category is text with a CHECK rather than a native enum type: the entity maps
-- it with @Enumerated(STRING), which Hibernate validates as a character column.
CREATE TABLE wants (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    message  VARCHAR(255) NOT NULL,
    category VARCHAR(16)  NOT NULL,
    user_id  BIGINT       NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_wants_category CHECK (category IN ('FOOD', 'GAME', 'MOVIE', 'TRIP')),
    CONSTRAINT fk_wants_user FOREIGN KEY (user_id) REFERENCES users (id)
);
